/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeTopicIdRouteImport } from './routes/practice.$topicId'
import { Route as LearnTopicIdRouteImport } from './routes/learn.$topicId'
import { Route as FeedbackTopicIdRouteImport } from './routes/feedback.$topicId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTopicIdRoute = PracticeTopicIdRouteImport.update({
  id: '/practice/$topicId',
  path: '/practice/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicIdRoute = LearnTopicIdRouteImport.update({
  id: '/learn/$topicId',
  path: '/learn/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackTopicIdRoute = FeedbackTopicIdRouteImport.update({
  id: '/feedback/$topicId',
  path: '/feedback/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/feedback/$topicId': typeof FeedbackTopicIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/practice/$topicId': typeof PracticeTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/feedback/$topicId': typeof FeedbackTopicIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/practice/$topicId': typeof PracticeTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/feedback/$topicId': typeof FeedbackTopicIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/practice/$topicId': typeof PracticeTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/live'
    | '/onboarding'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/feedback/$topicId'
    | '/learn/$topicId'
    | '/practice/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/live'
    | '/onboarding'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/feedback/$topicId'
    | '/learn/$topicId'
    | '/practice/$topicId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/live'
    | '/onboarding'
    | '/privacy'
    | '/progress'
    | '/settings'
    | '/terms'
    | '/feedback/$topicId'
    | '/learn/$topicId'
    | '/practice/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  FeedbackTopicIdRoute: typeof FeedbackTopicIdRoute
  LearnTopicIdRoute: typeof LearnTopicIdRoute
  PracticeTopicIdRoute: typeof PracticeTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$topicId': {
      id: '/practice/$topicId'
      path: '/practice/$topicId'
      fullPath: '/practice/$topicId'
      preLoaderRoute: typeof PracticeTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topicId': {
      id: '/learn/$topicId'
      path: '/learn/$topicId'
      fullPath: '/learn/$topicId'
      preLoaderRoute: typeof LearnTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$topicId': {
      id: '/feedback/$topicId'
      path: '/feedback/$topicId'
      fullPath: '/feedback/$topicId'
      preLoaderRoute: typeof FeedbackTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  FeedbackTopicIdRoute: FeedbackTopicIdRoute,
  LearnTopicIdRoute: LearnTopicIdRoute,
  PracticeTopicIdRoute: PracticeTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
